# Generated by Django 5.0 on 2023-12-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
