# Generated by Django 5.0 on 2024-01-13 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0004_alter_sensor_tipo_experimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_experimento', models.CharField(default='Monitoramento de chamas', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='tipo_experimento',
        ),
        migrations.AddField(
            model_name='sensor',
            name='experimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto_saas.experimento'),
        ),
    ]
