# Generated by Django 5.0 on 2024-01-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0005_experimento_remove_sensor_tipo_experimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='tipo_experimento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
