# Generated by Django 5.0 on 2024-01-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0007_alter_placa_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='mqtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_saas.mqtt'),
        ),
    ]
