# Generated by Django 5.0 on 2024-01-21 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0009_remove_placa_wifi_wifi_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placa',
            name='mqtt',
        ),
        migrations.AddField(
            model_name='mqtt',
            name='placa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto_saas.placa'),
        ),
    ]
