# Generated by Django 5.0 on 2024-01-21 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0010_remove_placa_mqtt_mqtt_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='placa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto_saas.placa'),
        ),
    ]
