# Generated by Django 5.0 on 2024-01-21 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0011_alter_mqtt_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='placa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto_saas.placa'),
        ),
    ]
