# Generated by Django 5.0 on 2024-01-24 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0012_alter_mqtt_placa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topicos',
            name='mqtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_saas.mqtt'),
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mqtt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='projeto_saas.mqtt')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='projeto_saas.placa')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='projeto_saas.sensor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
                ('wifi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='projeto_saas.wifi')),
            ],
        ),
    ]
