# Generated by Django 5.0 on 2024-01-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0013_alter_mqtt_usuario_alter_topicos_mqtt_configuracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='intervalo_leitura',
        ),
    ]
