# Generated by Django 5.0 on 2024-02-03 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0016_alter_sensor_tipo_sensor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placa_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placa',
            name='modelo',
            field=models.CharField(choices=[('ESP32', 'ESP32'), ('ARDUINO', 'Arduino')], default='ESP32', max_length=100),
        ),
    ]
