# Generated by Django 5.0 on 2024-02-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_saas', '0017_placa_usuario_alter_placa_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='modelo',
            field=models.CharField(choices=[('ESP32', 'ESP32'), ('ARDUINO', 'Arduino')], max_length=100, null=True),
        ),
    ]
